# Generated by Django 5.2.1 on 2025-06-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_patientaccount_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=20)),
                ('primary', models.CharField(max_length=120)),
                ('last_visit', models.DateTimeField()),
                ('next_visit', models.DateTimeField()),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_as_of_today', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_condition', models.CharField(max_length=1000)),
                ('suitable_specialists', models.CharField(max_length=300)),
                ('communicate_with_patient', models.CharField(max_length=500)),
                ('facilitate_referral_process', models.CharField(max_length=250)),
                ('follow_up', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='number_of_visits',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
