# Generated by Django 5.2.1 on 2025-06-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_patientbalance_referrals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientaccount',
            old_name='primary',
            new_name='primary_doctor',
        ),
    ]
